name: GitHub Secrets

on:
  workflow_dispatch:

environment:


jobs:
  deployment:
    runs-on: windows-latest
    steps:  
      - name: Print Secret
        run: |
            echo "APP_SECRET: ${{ secrets.MY_SECRET_KEY  }}"
            echo "i_dont_exist: ${{ secrets.i_dont_exist  }}"
            
      - name: Print Secret as an environment variable
        run: |
            echo "APP_SECRET: $MY_SECRET_KEY"
        env:
            APP_SECRET: ${{ secrets.MY_SECRET_KEY }}