name: Simple CI Workflow

on:
  push:
    branches: [main]

jobs:
  test:
    name: Run Tests
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Tests
        run: |
          echo "Running tests..."
          echo " All tests passed!"

  build:
    name: Build Project
    runs-on: windows-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Application
        run: |
          echo "Building the app..."
          echo " Build successful!"
